apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
      version: green
  template:
    metadata:
      labels:
        app: python-app
        version: green
    spec:
      containers:
      - name: python-app
        image: thenameisnani/python-app:green
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"