apiVersion: v1
kind: Service
metadata:
  name: colour-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: python-app
    version: blue  # Initial active version